src/Entity/FicheClient.php
<?php

namespace App\Entity;

use App\Repository\FicheClientRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=FicheClientRepository::class)
 */
class FicheClient
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom_client;

    /**
     * @ORM\Column(type="bigint")
     */
    private $tel_client;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email_client;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $raison_sociale;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $activite;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $site_web;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $referencement;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomClient(): ?string
    {
        return $this->nom_client;
    }

    public function setNomClient(string $nom_client): self
    {
        $this->nom_client = $nom_client;

        return $this;
    }

    public function getTelClient(): ?string
    {
        return $this->tel_client;
    }

    public function setTelClient(string $tel_client): self
    {
        $this->tel_client = $tel_client;

        return $this;
    }

    public function getEmailClient(): ?string
    {
        return $this->email_client;
    }

    public function setEmailClient(string $email_client): self
    {
        $this->email_client = $email_client;

        return $this;
    }

    public function getRaisonSociale(): ?string
    {
        return $this->raison_sociale;
    }

    public function setRaisonSociale(string $raison_sociale): self
    {
        $this->raison_sociale = $raison_sociale;

        return $this;
    }

    public function getActivite(): ?string
    {
        return $this->activite;
    }

    public function setActivite(string $activite): self
    {
        $this->activite = $activite;

        return $this;
    }

    public function getSiteWeb(): ?string
    {
        return $this->site_web;
    }

    public function setSiteWeb(?string $site_web): self
    {
        $this->site_web = $site_web;

        return $this;
    }

    public function getReferencement(): ?string
    {
        return $this->referencement;
    }

    public function setReferencement(string $referencement): self
    {
        $this->referencement = $referencement;

        return $this;
    }
}

src/Entity/Ficheclient.php
<?php

namespace App\Entity;

use App\Repository\FicheclientRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use mysql_xdevapi\Collection;

/**
 * @ORM\Entity(repositoryClass=FicheclientRepository::class)
 */
class Ficheclient
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nomclient;

    /**
     * @ORM\Column(type="bigint")
     */
    private $telclient;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $emailcli;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $activite;

    /**
     * @ORM\Column(type="boolean")
     */
    private $siteexistant;

    /**
     * @ORM\Column(type="boolean")
     */
    private $referencement;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $raisonsociale;

    /**
     * @var ArrayCollection|Collection
     *
     * @ORM\OneToOne(targetEntity=Ficheprospect::class, mappedBy="client", cascade={"persist", "remove"})
     */
    private $ficheprospect;

    /**
     * @var ArrayCollection|Collection
     *
     * @ORM\OneToOne(targetEntity=Ficherendezvous::class, mappedBy="entreprise", cascade={"persist", "remove"})
     */
    private $ficherendezvous;

    public function __toString()
    {
        return $this->getNomclient().' - '.$this->getRaisonsociale();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomclient(): ?string
    {
        return $this->nomclient;
    }

    public function setNomclient(string $nomclient): self
    {
        $this->nomclient = $nomclient;

        return $this;
    }

    public function getTelclient(): ?string
    {
        return $this->telclient;
    }

    public function setTelclient(string $telclient): self
    {
        $this->telclient = $telclient;

        return $this;
    }

    public function getEmailcli(): ?string
    {
        return $this->emailcli;
    }

    public function setEmailcli(string $emailcli): self
    {
        $this->emailcli = $emailcli;

        return $this;
    }

    public function getActivite(): ?string
    {
        return $this->activite;
    }

    public function setActivite(string $activite): self
    {
        $this->activite = $activite;

        return $this;
    }

    public function getSiteexistant(): ?bool
    {
        return $this->siteexistant;
    }

    public function setSiteexistant(bool $siteexistant): self
    {
        $this->siteexistant = $siteexistant;

        return $this;
    }



    public function getRaisonsociale(): ?string
    {
        return $this->raisonsociale;
    }

    public function setRaisonsociale(string $raisonsociale): self
    {
        $this->raisonsociale = $raisonsociale;

        return $this;
    }

    public function getReferencement(): ?bool
    {
        return $this->referencement;
    }

    public function setReferencement(bool $referencement): self
    {
        $this->referencement = $referencement;

        return $this;
    }

    public function getFicheprospect(): ?Ficheprospect
    {
        return $this->ficheprospect;
    }

    public function setFicheprospect(?Ficheprospect $ficheprospect): self
    {
        // unset the owning side of the relation if necessary
        if ($ficheprospect === null && $this->ficheprospect !== null) {
            $this->ficheprospect->setClient(null);
        }

        // set the owning side of the relation if necessary
        if ($ficheprospect !== null && $ficheprospect->getClient() !== $this) {
            $ficheprospect->setClient($this);
        }

        $this->ficheprospect = $ficheprospect;

        return $this;
    }

    public function getFicherendezvous(): ?Ficherendezvous
    {
        return $this->ficherendezvous;
    }

    public function setFicherendezvous(?Ficherendezvous $ficherendezvous): self
    {
        // unset the owning side of the relation if necessary
        if ($ficherendezvous === null && $this->ficherendezvous !== null) {
            $this->ficherendezvous->setEntreprise(null);
        }

        // set the owning side of the relation if necessary
        if ($ficherendezvous !== null && $ficherendezvous->getEntreprise() !== $this) {
            $ficherendezvous->setEntreprise($this);
        }

        $this->ficherendezvous = $ficherendezvous;

        return $this;
    }

}

src/Form/FicheClientType.php
<?php

namespace App\Form;

use App\Entity\FicheClient;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class FicheClientType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom_client')
            ->add('tel_client')
            ->add('email_client')
            ->add('raison_sociale')
            ->add('activite')
            ->add('site_web')
            ->add('referencement')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => FicheClient::class,
        ]);
    }
}

src/Form/FicheclientType.php
<?php

namespace App\Form;

use App\Entity\Ficheclient;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class FicheclientType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nomclient')
            ->add('telclient')
            ->add('emailcli')
            ->add('activite')
            ->add('raisonsociale')
            ->add('siteexistant')
            ->add('referencement')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Ficheclient::class,
        ]);
    }
}

src/Controller/FicheClientController.php
<?php

namespace App\Controller;

use App\Entity\FicheClient;
use App\Form\FicheClientType;
use App\Repository\FicheClientRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/fiche/client")
 */
class FicheClientController extends AbstractController
{
    /**
     * @Route("/fiche_client", name="fiche_client_index", methods={"GET"})
     */
    public function index(FicheClientRepository $ficheClientRepository): Response
    {
        return $this->render('fiche_client/index.html.twig', [
            'fiche_clients' => $ficheClientRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="fiche_client_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $ficheClient = new FicheClient();
        $form = $this->createForm(FicheClientType::class, $ficheClient);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($ficheClient);
            $entityManager->flush();

            return $this->redirectToRoute('fiche_client_index');
        }

        return $this->render('fiche_client/new.html.twig', [
            'fiche_client' => $ficheClient,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="fiche_client_show", methods={"GET"})
     */
    public function show(FicheClient $ficheClient): Response
    {
        return $this->render('fiche_client/show.html.twig', [
            'fiche_client' => $ficheClient,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="fiche_client_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, FicheClient $ficheClient): Response
    {
        $form = $this->createForm(FicheClientType::class, $ficheClient);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('fiche_client_index');
        }

        return $this->render('fiche_client/edit.html.twig', [
            'fiche_client' => $ficheClient,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="fiche_client_delete", methods={"POST"})
     */
    public function delete(Request $request, FicheClient $ficheClient): Response
    {
        if ($this->isCsrfTokenValid('delete'.$ficheClient->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($ficheClient);
            $entityManager->flush();
        }

        return $this->redirectToRoute('fiche_client_index');
    }
}

templates/fiche_client/_delete_form.html.twig
<form method="post" action="{{ path('fiche_client_delete', {'id': fiche_client.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ fiche_client.id) }}">
    <button class="btn">Delete</button>
</form>

templates/fiche_client/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/fiche_client/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit FicheClient{% endblock %}

{% block body %}
    <h1>Edit FicheClient</h1>

    {{ include('fiche_client/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('fiche_client_index') }}">back to list</a>

    {{ include('fiche_client/_delete_form.html.twig') }}
{% endblock %}

templates/fiche_client/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}FicheClient index{% endblock %}

{% block body %}
    <h1>FicheClient index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom_client</th>
                <th>Tel_client</th>
                <th>Email_client</th>
                <th>Raison_sociale</th>
                <th>Activite</th>
                <th>Site_web</th>
                <th>Referencement</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for fiche_client in fiche_clients %}
            <tr>
                <td>{{ fiche_client.id }}</td>
                <td>{{ fiche_client.nomClient }}</td>
                <td>{{ fiche_client.telClient }}</td>
                <td>{{ fiche_client.emailClient }}</td>
                <td>{{ fiche_client.raisonSociale }}</td>
                <td>{{ fiche_client.activite }}</td>
                <td>{{ fiche_client.siteWeb }}</td>
                <td>{{ fiche_client.referencement }}</td>
                <td>
                    <a href="{{ path('fiche_client_show', {'id': fiche_client.id}) }}">show</a>
                    <a href="{{ path('fiche_client_edit', {'id': fiche_client.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="9">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('fiche_client_new') }}">Create new</a>

    git
                    <table class="table table-hover text-nowrap">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>User</th>
                            <th>Date</th>
                            <th>Status</th>
                            <th>Reason</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td>183</td>
                            <td>John Doe</td>
                            <td>11-7-2014</td>
                            <td><span class="tag tag-success">Approved</span></td>
                            <td>Bacon ipsum dolor sit amet salami venison chicken flank fatback doner.</td>
                        </tr>
                        <tr>
                            <td>219</td>
                            <td>Alexander Pierce</td>
                            <td>11-7-2014</td>
                            <td><span class="tag tag-warning">Pending</span></td>
                            <td>Bacon ipsum dolor sit amet salami venison chicken flank fatback doner.</td>
                        </tr>
                        <tr>
                            <td>657</td>
                            <td>Bob Doe</td>
                            <td>11-7-2014</td>
                            <td><span class="tag tag-primary">Approved</span></td>
                            <td>Bacon ipsum dolor sit amet salami venison chicken flank fatback doner.</td>
                        </tr>
                        <tr>
                            <td>175</td>
                            <td>Mike Doe</td>
                            <td>11-7-2014</td>
                            <td><span class="tag tag-danger">Denied</span></td>
                            <td>Bacon ipsum dolor sit amet salami venison chicken flank fatback doner.</td>
                        </tr>
                        </tbody>
                    </table>
                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->
        </div>
    </div>
{% endblock %}

templates/fiche_client/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New FicheClient{% endblock %}

{% block body %}
    <h1>Create new FicheClient</h1>

    {{ include('fiche_client/_form.html.twig') }}

    <a href="{{ path('fiche_client_index') }}">back to list</a>
{% endblock %}

templates/fiche_client/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}FicheClient{% endblock %}

{% block body %}
    <h1>FicheClient</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ fiche_client.id }}</td>
            </tr>
            <tr>
                <th>Nom_client</th>
                <td>{{ fiche_client.nomClient }}</td>
            </tr>
            <tr>
                <th>Tel_client</th>
                <td>{{ fiche_client.telClient }}</td>
            </tr>
            <tr>
                <th>Email_client</th>
                <td>{{ fiche_client.emailClient }}</td>
            </tr>
            <tr>
                <th>Raison_sociale</th>
                <td>{{ fiche_client.raisonSociale }}</td>
            </tr>
            <tr>
                <th>Activite</th>
                <td>{{ fiche_client.activite }}</td>
            </tr>
            <tr>
                <th>Site_web</th>
                <td>{{ fiche_client.siteWeb }}</td>
            </tr>
            <tr>
                <th>Referencement</th>
                <td>{{ fiche_client.referencement }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('fiche_client_index') }}">back to list</a>

    <a href="{{ path('fiche_client_edit', {'id': fiche_client.id}) }}">edit</a>

    {{ include('fiche_client/_delete_form.html.twig') }}
{% endblock %}